apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: py-func-live
    apps.tanzu.vmware.com/workload-type: web
  name: py-func-live
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
  build:
    env:
      - name: BP_FUNCTION
        value: func.main