apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/workload-type: web
  name: py-sb
spec:
  build:
    env:
      - name: BP_FUNCTION
        value: func.main
  env:
    - name: SERVICE_BINDING_ROOT
      value: "/bindings"
  serviceClaims:
    - name: postgres
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: dev1-claim