apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: py-func-event
    apps.tanzu.vmware.com/workload-type: web
  name: py-func-event
spec:
  build:
    env:
    - name: BP_FUNCTION
      value: func.main
  env:
    - name: PYTHONUNBUFFERED
      value: "TRUE"
