apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: py-simple-api-doc
  name: py-simple-api-doc
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: api_descriptor
      value:
        description: Python Hello
        location:
          path: /swagger.json
        owner: demo
        system: dev
        type: openapi